server:
  port: 10010
spring:
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      routes:
        - id: auth-service #唯一标志
          uri: lb://auth #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/auth/** #判断是否以auth开头
        - id: user-service #唯一标志
          uri: lb://user #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/user/** #判断是否以user开头
        - id: file-service #唯一标志
          uri: lb://file #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/file/** #判断是否以file开头
        - id: comment-service #唯一标志
          uri: lb://comment #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/comment/** #判断是否以comment开头
        - id: like-service #唯一标志
          uri: lb://like #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/like/** #判断是否以like开头
  main:
    web-application-type: reactive
  application:
    name: gateway

